### ISSUE TITLE
Some more Growth Frameworks for Engineers

### ISSUE THREAD

**Issue by chapati23** [benjmin-r/squeakyvessel.com#6]
Hey 🙂
just discovered your collection of career paths today, great stuff!

we've compiled a similar list a while back when we were starting to work on our first framework, i think there may be a few links in there that you don't have in your list so far

feel free to copy/pasta 🍝

https://www.notion.so/brickblock/Growth-Frameworks-for-Engineers-63caaa58edcb41c0ba28a0cf929f24db

P.S. Feel free to close this issue after you've read it, just didn't have enough time to do a full diff between our lists and create a PR unfortunately..

**Comment by benjmin-r** [comment]
Thank you @chapati23, for taking the time to send me this great list you got there. Will have a look and surely add some of yours
